services:
  - type: web
    name: habit-tracker
    env: ruby
    buildCommand: |
      chmod +x ./bin/render-build.sh
      export RAILS_ENV=production
      export RAILS_MASTER_KEY=$RAILS_MASTER_KEY
      ./bin/render-build.sh
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: habit-tracker-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: habit-tracker-redis
          property: connectionString
    healthCheckPath: /up
    autoDeploy: true
    buildFilter:
      paths:
        - package.json
        - package-lock.json
        - Gemfile
        - Gemfile.lock
        - config/**
        - app/**
        - bin/**
        - lib/**
        - public/**
        - vendor/**
        - Dockerfile
        - render.yaml

databases:
  - name: habit-tracker-db
    databaseName: habit_tracker
    user: habit_tracker
    plan: free

services:
  - type: redis
    name: habit-tracker-redis
    plan: free
    maxmemoryPolicy: noeviction
    ipAllowList: []